### ISSUE TITLE
CI - Adding continuous Integration for the project

### ISSUE THREAD

**Issue by andy2great** [andy2great/NX-Generatorz#22]
Currently there is nothing that prevents a PR that does not build to be merge in the main branch.

We would like to ensure the following:
- Lint respected
- Test passing
- Build passing

If all those works, we can allow to merge

**Comment by MeatCow** [comment]
I agree with the last 2 points, however would it be acceptable to simply apply a prettify filter on our code during the CI, instead of a lint?
